dataset: MNIST
device: [0]

ipc: 800
syn_steps: 100
expert_epochs: 2
lr_img: 50
lr_teacher: 0.01

buffer_path: ./buffers_DATM/

data_path: ./MNIST/
ema_decay: 0.995
Iteration: 10
batch_syn: 100

# wandb
project: MNIST_ipc1000

num_eval: 1
eval_it: 10
skip_first_eva: True

lr_y: 10.
Momentum_y: 0.9
threshold: 1.
pix_init: real
Sequential_Generation: False
batch_train: 128
min_start_epoch: 20
max_start_epoch: 30
lr_lr: 0.00001
zca: True

epoch_eval_train: 20
